name: deploy lambda function
on:
  push:
    branches:
      - test_actions
      - main
    paths:
      - 'aws/demo-aws-lambda/functions/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
            - dev
            - staging
            - prod

env:
  CONFIG_FILE: .github/config/deployment-config.yml
  oidc-role-arn: "arn:aws:iam::734237051973:role/github-oidc-role"
  AWS_REGION: "us-east-1"
  ENVIRONMENT: east

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            nodejs-app:            'aws/demo-aws-lambda/functions/nodejs-app/**'
            nodejs-app-2:            'aws/demo-aws-lambda/functions/nodejs-app-2/**'
  deploy:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function_key: ${{fromJSON(needs.detect-changes.outputs.matrix)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd aws/demo-aws-lambda/functions/${{ matrix.function_key }}
          npm install

    #   - name: Deploy Lambda function
    #     if: ${{ needs.detect-changes.outputs.matrix[matrix.function_key] == 'true' }}
    #     run: |
    #       cd aws/demo-aws-lambda/functions/${{ matrix.function_key }}
    #       zip -r ../../nodeApp.zip .
    #       aws lambda update-function-code --function-name ${{ matrix.function_key }} --zip-file fileb://../../nodeApp.zip --region ${{ env.AWS_REGION }}
